name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # Temurin is widely supported
          java-version: '17'

      - name: Compile project
        run: mvn compile

      - name: All tests
        id: all-tests
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: All tests
          setup-command: mvn compile
          command: mvn test
          timeout: 10
          max-score: 1

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          ALL-TESTS_RESULTS: "${{ steps.all-tests.outputs.result }}"
        with:
          runners: all-tests

